spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: java
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.study.board
#  mapper.xml의 위치를 매핑시켜주는것
  mapper-locations: classpath:mybatis/mappers/**/*.xml
