spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:mysql://localhost:3306~
    url: jdbc:log4jdbc:mysql://localhost:3306/board?useUnicode=yes&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Seoul
    username: root
    password: java

mybatis:
  type-aliases-package: com.study.board
#  mapper.xml의 위치를 매핑시켜주는것
  mapper-locations: classpath:mybatis/mappers/**/*.xml

# log4jdbc, mybatis console log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: INFO     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection : OFF  # 커넥션 확인가능 (커넥션 누수를 해결하는데 도움이 된다.)
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE    # 로그 레벨 : TRACE -> DEBUG -> INFO -> WARN -> ERROR -> FATAL 순서